DEFINE_PATCH_FUNCTION a7#normalize_table BEGIN
    SET num_added = 0
    COUNT_2DA_COLS num_cols
    READ_2DA_ENTRIES_NOW table 1
    READ_2DA_ENTRY_FORMER table 1 0 default
    FOR (row = 0; row < table; ++row) BEGIN
        READ_2DA_ENTRY_FORMER table row 0 line
        FOR (col = 1; col < num_cols && VARIABLE_IS_SET $table(~%row%~ ~%col%~); ++col) BEGIN
            READ_2DA_ENTRY_FORMER table row col v
            TEXT_SPRINT line ~%line% %v%~
        END
        // fill in missing data
        PATCH_IF (row = 2) BEGIN  // header
            FOR (; col < num_cols - 1; ++col) BEGIN
                TEXT_SPRINT line ~%line% %col%~
                SET num_added += 1
            END
        END ELSE PATCH_IF (row > 2) BEGIN  // content
            FOR (; col < num_cols; ++col) BEGIN
                TEXT_SPRINT line ~%line% %default%~
                SET num_added += 1
            END
        END
        TEXT_SPRINT $lines(~%row%~) ~%line%%LNL%~
        SET $lines(~%row%~ ~size~) = STRING_LENGTH $lines(~%row%~)
    END
    // write normalized table to buffer
    PATCH_IF (num_added > 0) BEGIN
        DELETE_BYTES 0 BUFFER_LENGTH
        FOR (row = 0 pos = 0; row < table; ++row) BEGIN
            SET size = $lines(~%row%~ ~size~)
            INSERT_BYTES pos size
            WRITE_ASCIIE pos $lines(~%row%~) (size)
            SET pos += size
        END
    END
END
