INCLUDE ~subrace/lib/functions.tph~
INCLUDE ~subrace/lib/lua_functions.tph~
INCLUDE ~subrace/lib/subrace_lua.tph~

INCLUDE ~subrace/lib/initial_area_patch.tph~
INCLUDE ~subrace/lib/asset_copy.tph~
INCLUDE ~subrace/lib/subrace_fragments/desc_appends.tph~
INCLUDE ~subrace/lib/subrace_fragments/subrace_spells.tph~
INCLUDE ~subrace/lib/subrace_fragments/npc_patching.tph~
INCLUDE ~subrace/lib/subrace_fragments/ui.tph~
