
INCLUDE ~subrace/lib/functions.tph~
INCLUDE ~subrace/lib/lua_functions.tph~
INCLUDE ~subrace/lib/subrace_lua.tph~

LAF ADD_SPLPROT_ENTRY INT_VAR value_hex=1 STR_VAR label="OUTDOOR"    definition="0x106  0x1  8" RET outdoor   =index END
LAF ADD_SPLPROT_ENTRY INT_VAR value_hex=1 STR_VAR label="NOTOUTDOOR" definition="0x106  0x1  9" RET notoutdoor=index END

LAF ADD_IDS_ENTRY
  INT_VAR minValue = 0 preferredValue = 140
  STR_VAR idsFile = "splstate.ids" identifier = "CRE_BLINDED_IWD"
  RET CRE_BLINDED_IWD = value
END

CLEAR_IDS_MAP

/* Baldur */
ACTION_DEFINE_ASSOCIATIVE_ARRAY campscr BEGIN ~baldur~   => ~~ END
ACTION_DEFINE_ASSOCIATIVE_ARRAY campscr BEGIN ~baldur25~ => ~~ END
ACTION_IF (FILE_EXISTS_IN_GAME ~campaign.2da~) BEGIN
	COPY_EXISTING ~campaign.2da~ ~override~
		COUNT_2DA_ROWS 4 rws
		FOR ( i = 0 ; i < rws ; ++i ) BEGIN
			READ_2DA_ENTRY i 1 4 scrp
			TO_UPPER scrp
			PATCH_IF (!VARIABLE_IS_SET $campscr(~%scrp%~)) BEGIN
				DEFINE_ASSOCIATIVE_ARRAY campscr BEGIN ~%scrp%~ => ~~ END
			END
		END
		BUT_ONLY
END

ACTION_PHP_EACH campscr AS wbcs => dummy BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%wbcs%.bcs~ THEN BEGIN
		EXTEND_TOP ~%wbcs%.bcs~ ~subrace/baf/appendba.baf~
	END
END


ACTION_IF (NOT FILE_EXISTS_IN_GAME ~sunscoh.bam~) BEGIN
	COPY ~subrace/bam/sunscoh.bam~ ~override/sunscoh.bam~
END
COPY ~subrace/bam/srsubico.bam~ ~override~
ACTION_IF (NOT FILE_EXISTS_IN_GAME ~dff_p39.wav~) BEGIN
	COPY ~subrace/wav/dff_p39.wav~ ~override~
END
ACTION_IF (NOT FILE_EXISTS_IN_GAME ~idpr113b.bam~) BEGIN
	COPY ~subrace/bam/idpr113b.bam~ ~override~
END
ACTION_IF (NOT FILE_EXISTS_IN_GAME ~idpr113c.bam~) BEGIN
	COPY ~subrace/bam/idpr113c.bam~ ~override~
END

LAF APPEND_STATDESC_ENTRY INT_VAR strref=text_aasimar   STR_VAR bam_file="SRSUBICO" RET text_aasimar=index   Ztext_aasimar=strref   END
LAF APPEND_STATDESC_ENTRY INT_VAR strref=text_drow      STR_VAR bam_file="SRSUBICO" RET text_drow=index      Ztext_drow=strref      END
LAF APPEND_STATDESC_ENTRY INT_VAR strref=text_dwfduerg  STR_VAR bam_file="SRSUBICO" RET text_dwfduerg=index  Ztext_dwfduerg=strref  END
LAF APPEND_STATDESC_ENTRY INT_VAR strref=text_dwfgold   STR_VAR bam_file="SRSUBICO" RET text_dwfgold=index   Ztext_dwfgold=strref   END
LAF APPEND_STATDESC_ENTRY INT_VAR strref=text_hflhide   STR_VAR bam_file="SRSUBICO" RET text_hflhide=index   Ztext_hflhide=strref   END
LAF APPEND_STATDESC_ENTRY INT_VAR strref=text_hflstrong STR_VAR bam_file="SRSUBICO" RET text_hflstrong=index Ztext_hflstrong=strref END
LAF APPEND_STATDESC_ENTRY INT_VAR strref=text_svirfn    STR_VAR bam_file="SRSUBICO" RET text_svirfn=index    Ztext_svirfn=strref    END
LAF APPEND_STATDESC_ENTRY INT_VAR strref=text_tiefling  STR_VAR bam_file="SRSUBICO" RET text_tiefling=index  Ztext_tiefling=strref  END
LAF APPEND_STATDESC_ENTRY INT_VAR strref=text_wild_elf  STR_VAR bam_file="SRSUBICO" RET text_wild_elf=index  Ztext_wild_elf=strref  END
LAF APPEND_STATDESC_ENTRY INT_VAR strref=text_moon_elf  STR_VAR bam_file="SRSUBICO" RET text_moon_elf=index  Ztext_moon_elf=strref  END
LAF APPEND_STATDESC_ENTRY INT_VAR strref=text_feyri  STR_VAR bam_file="SRSUBICO" RET text_feyri=index  Ztext_feyri=strref  END
LAF APPEND_STATDESC_ENTRY INT_VAR strref=text_halfdrow  STR_VAR bam_file="SRSUBICO" RET text_halfdrow=index  Ztext_halfdrow=strref  END

COPY ~subrace/lua/m_zzsubr.lua~ ~override~ EVALUATE_BUFFER
//BLOCK SUBRACE SPELLS
COPY ~subrace/spl/spell.spl~ ~override/sr_aasim.spl~
  //Portrait icon
  LPF ADD_SPELL_EFFECT INT_VAR opcode=142 target=2 timing=9 parameter2=text_aasimar END
   //Skin color
  PATCH_IF ( sr_colors = 1 ) BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode=7 target=2 timing=9  parameter1=154 parameter2=3 END
  END
   //Wisdom +1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=49 target=2 timing=1  parameter1=1 END
   //Charisma +1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=6 target=2 timing=1  parameter1=1 END
   //Acid resistance +15
  LPF ADD_SPELL_EFFECT INT_VAR opcode=27 target=2 timing=9 parameter1=15 END
   //Cold resistance +15
  LPF ADD_SPELL_EFFECT INT_VAR opcode=28 target=2 timing=9 parameter1=15 END
   //Electricity resistance +15
  LPF ADD_SPELL_EFFECT INT_VAR opcode=29 target=2 timing=9 parameter1=15 END
   //Infravision
  LPF ADD_SPELL_EFFECT INT_VAR opcode=63 target=2 timing=9 END
  //Give innate ability
  LPF ADD_SPELL_EFFECT INT_VAR opcode=171 target=2 timing=9  STR_VAR resource="srsnscoh" END
  //XP bonus - 95%
  LPF ADD_SPELL_EFFECT INT_VAR opcode=104 target=2 timing=9 parameter1=95 parameter2=2 END

COPY ~subrace/spl/spell.spl~ ~override/sr_tiefl.spl~
  //Portrait icon
  LPF ADD_SPELL_EFFECT INT_VAR opcode=142 target=2 timing=9 parameter2=text_tiefling END
   //Skin color
  PATCH_IF ( sr_colors = 1 ) BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode=7 target=2 timing=9  parameter1=84 parameter2=3 END
   //Hair color
    LPF ADD_SPELL_EFFECT INT_VAR opcode=7 target=2 timing=9  parameter1=19 parameter2=6 END
  END
   //intelligence +1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=19 target=2 timing=1  parameter1=1 END
   //Dexterity +1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=15 target=2 timing=1  parameter1=1 END
   //Fire resistance +15
  LPF ADD_SPELL_EFFECT INT_VAR opcode=30 target=2 timing=9 parameter1=15 END
   //Cold resistance +15
  LPF ADD_SPELL_EFFECT INT_VAR opcode=28 target=2 timing=9 parameter1=15 END
   //Electricity resistance +15
  LPF ADD_SPELL_EFFECT INT_VAR opcode=29 target=2 timing=9 parameter1=15 END
   //Infravision
  LPF ADD_SPELL_EFFECT INT_VAR opcode=63 target=2 timing=9 END
  //Give innate ability
  LPF ADD_SPELL_EFFECT INT_VAR opcode=171 target=2 timing=9  STR_VAR resource="srblind" END
   //Charisma -1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=6 target=2 timing=1  parameter1="-1" END
  //XP bonus - 95%
  LPF ADD_SPELL_EFFECT INT_VAR opcode=104 target=2 timing=9 parameter1=95 parameter2=2 END

COPY ~subrace/spl/spell.spl~ ~override/sr_feyri.spl~
  //Portrait icon
  LPF ADD_SPELL_EFFECT INT_VAR opcode=142 target=2 timing=9 parameter2=text_feyri END
   //Skin color
  PATCH_IF ( sr_colors = 1 ) BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode=7 target=2 timing=9  parameter1=84 parameter2=3 END
   //Hair color
    LPF ADD_SPELL_EFFECT INT_VAR opcode=7 target=2 timing=9  parameter1=19 parameter2=6 END
  END
   //Charisma +1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=6 target=2 timing=1  parameter1=1 END
   //Dexterity +1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=15 target=2 timing=1  parameter1=1 END
   //Fire resistance +15
  LPF ADD_SPELL_EFFECT INT_VAR opcode=30 target=2 timing=9 parameter1=15 END
   //Cold resistance +15
  LPF ADD_SPELL_EFFECT INT_VAR opcode=28 target=2 timing=9 parameter1=15 END
   //Electricity resistance +15
  LPF ADD_SPELL_EFFECT INT_VAR opcode=29 target=2 timing=9 parameter1=15 END
  //Give innate ability
  LPF ADD_SPELL_EFFECT INT_VAR opcode=171 target=2 timing=9  STR_VAR resource="srblind" END
  //XP bonus - 95%
  LPF ADD_SPELL_EFFECT INT_VAR opcode=104 target=2 timing=9 parameter1=95 parameter2=2 END

COPY ~subrace/spl/spell.spl~ ~override/sr_drow.spl~
  //Portrait icon
  LPF ADD_SPELL_EFFECT INT_VAR opcode=142 target=2 timing=9 parameter2=text_drow END
   //Skin color
  PATCH_IF ( sr_colors = 1 ) BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode=7 target=2 timing=9  parameter1=182 parameter2=3 END
   //Hair color
    LPF ADD_SPELL_EFFECT INT_VAR opcode=7 target=2 timing=9  parameter1=79 parameter2=6 END
  END
  //Set spell state
  LPF ADD_SPELL_EFFECT INT_VAR opcode=328 target=2 timing=9  parameter2=%CRE_BLINDED_IWD% special=1  END
   //intelligence +1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=19 target=2 timing=1  parameter1=1 END
   //Charisma +1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=6 target=2 timing=1  parameter1=1 END
   //Find traps +10
  LPF ADD_SPELL_EFFECT INT_VAR opcode=91 target=2 timing=9 parameter1=10 END
   //Reputation
  LPF ADD_SPELL_EFFECT INT_VAR opcode=108 target=2 timing=1 parameter1="-2" END
   //Magic resistance 50%
  LPF ADD_SPELL_EFFECT INT_VAR opcode=166 target=2 timing=9 parameter1=50 END
   //Save vs. spells +1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=37 target=2 timing=9 parameter1=1 END
   //Give innate ability
  LPF ADD_SPELL_EFFECT INT_VAR opcode=171 target=2 timing=9  STR_VAR resource="srffire" END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=171 target=2 timing=9  STR_VAR resource="srffire" END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=171 target=2 timing=9  STR_VAR resource="srffire" END
   //Day blindness
  LPF ADD_SPELL_EFFECT INT_VAR opcode=272 target=2 timing=9 parameter1=6 parameter2=3  STR_VAR resource="srdblind" END
  //XP bonus - 90%
  LPF ADD_SPELL_EFFECT INT_VAR opcode=104 target=2 timing=9 parameter1=90 parameter2=2 END

COPY ~subrace/spl/spell.spl~ ~override/sr_hdrow.spl~
  //Portrait icon
  LPF ADD_SPELL_EFFECT INT_VAR opcode=142 target=2 timing=9 parameter2=text_halfdrow END
   //Skin color
  PATCH_IF ( sr_colors = 1 ) BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode=7 target=2 timing=9  parameter1=63 parameter2=3 END
   //Hair color
    LPF ADD_SPELL_EFFECT INT_VAR opcode=7 target=2 timing=9  parameter1=79 parameter2=6 END
  END
   //intelligence +1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=19 target=2 timing=1  parameter1=1 END
   //Find traps +5
  LPF ADD_SPELL_EFFECT INT_VAR opcode=91 target=2 timing=9 parameter1=10 END
  // 10% magic resistance
  LPF ADD_SPELL_EFFECT INT_VAR opcode=166 target=2 timing=9 parameter1=10 END
   //Give innate ability
  LPF ADD_SPELL_EFFECT INT_VAR opcode=171 target=2 timing=9  STR_VAR resource="srffire" END
  //XP bonus - 95%
  LPF ADD_SPELL_EFFECT INT_VAR opcode=104 target=2 timing=9 parameter1=95 parameter2=2 END

COPY ~subrace/spl/spell.spl~ ~override/sr_ewild.spl~
  //Portrait icon
  LPF ADD_SPELL_EFFECT INT_VAR opcode=142 target=2 timing=9 parameter2=text_wild_elf END
   //Skin color
  PATCH_IF ( sr_colors = 1 ) BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode=7 target=2 timing=9  parameter1=1 parameter2=3 END
   //Hair color
    LPF ADD_SPELL_EFFECT INT_VAR opcode=7 target=2 timing=9  parameter1=29 parameter2=6 END
  END
   //Constitution +1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=10 target=2 timing=1  parameter1=1 END
   //intlligence -1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=19 target=2 timing=1  parameter1="-1" END

COPY ~subrace/spl/spell.spl~ ~override/sr_emoon.spl~
  //Portrait icon
  LPF ADD_SPELL_EFFECT INT_VAR opcode=142 target=2 timing=9 parameter2=text_moon_elf END
   //Charisma +1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=6 target=2 timing=1  parameter1=1 END
   //Hide in shadows +10
  LPF ADD_SPELL_EFFECT INT_VAR opcode=275 target=2 timing=9 parameter1=10 END
   //Move silently +10
  LPF ADD_SPELL_EFFECT INT_VAR opcode=59 target=2 timing=9 parameter1=10 END
   //Constitution -1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=10 target=2 timing=1  parameter1="-1" END

COPY ~subrace/spl/spell.spl~ ~override/sr_hlstr.spl~
  //Portrait icon
  LPF ADD_SPELL_EFFECT INT_VAR opcode=142 target=2 timing=9 parameter2=text_hflstrong END
   // +1 axe star
  LPF ADD_SPELL_EFFECT INT_VAR opcode=233 target=2 timing=9 parameter1=1 parameter2=65628 END


COPY ~subrace/spl/spell.spl~ ~override/sr_hlgho.spl~
  //Portrait icon
  LPF ADD_SPELL_EFFECT INT_VAR opcode=142 target=2 timing=9 parameter2=text_hflhide END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=318 target=2 duration=1 parameter1=205 parameter2=115 STR_VAR resource=SR_HLGHO END
   //Find traps +5
  LPF ADD_SPELL_EFFECT INT_VAR opcode=91 target=2 timing=9 parameter1=5 END
   //Give innate ability
  LPF ADD_SPELL_EFFECT INT_VAR opcode=171 target=2 timing=9  STR_VAR resource="spcl412" END
  //LPF ADD_SPELL_EFFECT INT_VAR opcode=272 target=2 parameter1=12 parameter2=3 timing=9 STR_VAR resource=SR_HLGHO END

COPY ~subrace/spl/spell.spl~ ~override/sr_svirf.spl~
  //Portrait icon
  LPF ADD_SPELL_EFFECT INT_VAR opcode=142 target=2 timing=9 parameter2=text_svirfn END
   //Skin color
  PATCH_IF ( sr_colors = 1 ) BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode=7 target=2 timing=9  parameter1=10 parameter2=3 END
   //Hair color
    LPF ADD_SPELL_EFFECT INT_VAR opcode=7 target=2 timing=9  parameter1=0 parameter2=6 END
  END
   //Dexterity +1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=15 target=2 timing=1  parameter1=1 END
   //Wisdom +1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=49 target=2 timing=1  parameter1=1 END
   //Strength -1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=44 target=2 timing=1  parameter1="-1" END
   //Charisma -1
  //LPF ADD_SPELL_EFFECT INT_VAR opcode=6 target=2 timing=1  parameter1="-1" END
   //Magic resistance 40/45/50/55/60
  //LPF ADD_SPELL_EFFECT INT_VAR opcode=166 target=2 timing=9 parameter1=40 probability1=20  END
  //LPF ADD_SPELL_EFFECT INT_VAR opcode=166 target=2 timing=9 parameter1=45 probability1=40  probability2=21 END
  //LPF ADD_SPELL_EFFECT INT_VAR opcode=166 target=2 timing=9 parameter1=50 probability1=60  probability2=41 END
  //LPF ADD_SPELL_EFFECT INT_VAR opcode=166 target=2 timing=9 parameter1=55 probability1=80  probability2=61 END
  //LPF ADD_SPELL_EFFECT INT_VAR opcode=166 target=2 timing=9 parameter1=60 probability1=100 probability2=81 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=166 target=2 timing=9 parameter1=50 END
   //+2 Missile AC
  LPF ADD_SPELL_EFFECT INT_VAR opcode=0 target=2 timing=9  parameter1=2 parameter2=2 END
   //Non detection
  LPF ADD_SPELL_EFFECT INT_VAR opcode=7 target=2 timing=9  END
   //Save vs. all +1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=325 target=2 timing=9 parameter1=1 END
   //Attack bonus
  LPF ADD_SPELL_EFFECT INT_VAR opcode=177 target=2 timing=9 parameter1=161 parameter2=4  STR_VAR resource="srsvatk" END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=177 target=2 timing=9 parameter1=112 parameter2=4  STR_VAR resource="srsvatk" END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=177 target=2 timing=9 parameter1=111 parameter2=4  STR_VAR resource="srsvatk" END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=177 target=2 timing=9 parameter1=165 parameter2=4  STR_VAR resource="srsvatk" END
   //Find traps +10
  //LPF ADD_SPELL_EFFECT INT_VAR opcode=91 target=2 timing=9 parameter1=10 END
   //Hide in shadows +10
  LPF ADD_SPELL_EFFECT INT_VAR opcode=275 target=2 timing=9 parameter1=10 END
   //Hide in shadows no outdoors
  LPF ADD_SPELL_EFFECT INT_VAR opcode=272 target=2 timing=9 parameter1=6 parameter2=3  STR_VAR resource="srsvshd" END
   //Give innate ability
  LPF ADD_SPELL_EFFECT INT_VAR opcode=171 target=2 timing=9  STR_VAR resource="srsvmim" END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=171 target=2 timing=9  STR_VAR resource="srsvinv" END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=171 target=2 timing=9  STR_VAR resource="srsvblr" END
  //XP bonus - 85%
  LPF ADD_SPELL_EFFECT INT_VAR opcode=104 target=2 timing=9 parameter1=85 parameter2=2 END
  //Charisma -1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=6 target=2 timing=1  parameter1="-1" END
  //Charisma -1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=318 target=2 duration=1 parameter1=3 parameter2=133 STR_VAR resource=SR_SVIRF END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=6 target=2 timing=1  parameter1="-1" END
  

COPY ~subrace/spl/spell.spl~ ~override/sr_dwgld.spl~
  //Portrait icon
  LPF ADD_SPELL_EFFECT INT_VAR opcode=142 target=2 timing=9 parameter2=text_dwfgold END
   //Charisma +1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=6 target=2 timing=1  parameter1=1 END
   //Dexterity -1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=15 target=2 timing=1  parameter1="-1" END
   //+2 AC vs giants
  LPF ADD_SPELL_EFFECT INT_VAR opcode=177 target=2 timing=9 parameter1=5 parameter2=3  STR_VAR resource="srdwacg" END
   //Attack bonus
  LPF ADD_SPELL_EFFECT INT_VAR opcode=177 target=2 timing=9 parameter1=2 parameter2=4  STR_VAR resource="srsvatk" END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=177 target=2 timing=9 parameter1=172 parameter2=4  STR_VAR resource="srsvatk" END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=177 target=2 timing=9 parameter1=124 parameter2=4  STR_VAR resource="srsvatk" END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=177 target=2 timing=9 parameter1=116 parameter2=4  STR_VAR resource="srsvatk" END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=177 target=2 timing=9 parameter1=123 parameter2=4  STR_VAR resource="srsvatk" END

COPY ~subrace/spl/spell.spl~ ~override/sr_duerg.spl~
  //Portrait icon
  LPF ADD_SPELL_EFFECT INT_VAR opcode=142 target=2 timing=9 parameter2=text_dwfduerg END
   //Skin color
  PATCH_IF ( sr_colors = 1 ) BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode=7 target=2 timing=9  parameter1=63 parameter2=3 END
   //Hair color
    LPF ADD_SPELL_EFFECT INT_VAR opcode=7 target=2 timing=9  parameter1=5 parameter2=6 END
  END
  //Set spell state
  LPF ADD_SPELL_EFFECT INT_VAR opcode=328 target=2 timing=9  parameter2=%CRE_BLINDED_IWD% special=1  END
   //Find traps +10
  LPF ADD_SPELL_EFFECT INT_VAR opcode=91 target=2 timing=9 parameter1=10 END
   //Save vs. spells +1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=37 target=2 timing=9 parameter1=1 END
   //Move silently +20
  LPF ADD_SPELL_EFFECT INT_VAR opcode=59 target=2 timing=9 parameter1=20 END
   //+2 AC vs giants
  LPF ADD_SPELL_EFFECT INT_VAR opcode=177 target=2 timing=9 parameter1=5 parameter2=3  STR_VAR resource="srdwacg" END
   //Give innate ability
  LPF ADD_SPELL_EFFECT INT_VAR opcode=171 target=2 timing=9  STR_VAR resource="srsvinv" END
   //Infravision
  LPF ADD_SPELL_EFFECT INT_VAR opcode=63 target=2 timing=9 END
   //Reputation
  LPF ADD_SPELL_EFFECT INT_VAR opcode=108 target=2 timing=1 parameter1="-1" END
   //Day blindness
  LPF ADD_SPELL_EFFECT INT_VAR opcode=272 target=2 timing=9 parameter1=6 parameter2=3  STR_VAR resource="srdblind" END
  //XP bonus - 90%
  LPF ADD_SPELL_EFFECT INT_VAR opcode=104 target=2 timing=9 parameter1=90 parameter2=2 END
   //Charisma -1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=6 target=2 timing=1  parameter1="-1" END
  //Charisma -1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=318 target=2 duration=1 parameter1=3 parameter2=133 STR_VAR resource=SR_DUERG END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=6 target=2 timing=1  parameter1="-1" END

//BLOCKEND

//BLOCK ABILITY SPELLS
//SRSNSCOH (IDPR113)
ADD_PROJECTILE ~subrace/pro/idpro000.pro~
COPY ~subrace/spl/idpr113.spl~ ~override/srsnscoh.spl~
	SAY 0x08 @40
	SAY 0x50 @41
	LPM CONVERT_SPL_TO_INNATE
	LPF ALTER_SPELL_EFFECT INT_VAR match_opcode=324 opcode=318 STR_VAR resource="srsnscoh" END
	LPF ALTER_SPELL_HEADER INT_VAR projectile=idpro000 END
//SRBLIND  (SPWI106)
COPY_EXISTING ~spwi106.spl~ ~override/srblind.spl~
	LPM CONVERT_SPL_TO_INNATE
//SRFFIRE  (sppr116)  (sppr100)
COPY ~subrace/spl/sppr100.spl~ ~override/srffire.spl~
	SAY 0x08 @42
	SAY 0x50 @43
	LPM CONVERT_SPL_TO_INNATE
	LPF ALTER_SPELL_EFFECT INT_VAR match_opcode=318 STR_VAR resource="srffire" END
	LPF ALTER_SPELL_EFFECT INT_VAR match_opcode=206 STR_VAR resource="srffire" END
	LPF ALTER_SPELL_EFFECT INT_VAR match_opcode=139 parameter1=RESOLVE_STR_REF(@42) END
//SRSVMIM  (SPWI212) - Mirror Image
COPY_EXISTING ~spwi212.spl~ ~override/srsvmim.spl~
	LPM CONVERT_SPL_TO_INNATE
//SRSVINV  (spwi206) - Invisibility
COPY_EXISTING ~spwi206.spl~ ~override/srsvinv.spl~
	LPM CONVERT_SPL_TO_INNATE
	LPF ALTER_SPELL_HEADER INT_VAR target=5 speed=0 END
	LPF ALTER_SPELL_EFFECT INT_VAR match_opcode="-1" target=1 END
	LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete=174 END
	WRITE_SHORT 0x22 0
//SRSVBLR  (spwi201) - Blur
COPY_EXISTING ~spwi201.spl~ ~override/srsvblr.spl~
	LPM CONVERT_SPL_TO_INNATE
//BLOCKEND

//BLOCK SPELLS XP
//SRSVATK.EFF - +1 THAC0
COPY ~subrace/eff/effect.eff~ ~override/srsvatk.eff~
  WRITE_LONG  0x10 278
  WRITE_LONG  0x14 2
  WRITE_LONG  0x1c 1
  WRITE_LONG  0x24 1
  WRITE_SHORT 0x2c 100

//SRDWACG.EFF - +4 AC
COPY ~subrace/eff/effect.eff~ ~override/srdwacg.eff~
  WRITE_LONG  0x10 0
  WRITE_LONG  0x14 2
  WRITE_LONG  0x1c 4
  WRITE_LONG  0x24 1
  WRITE_SHORT 0x2c 100

//Drow blindness
//SRDBLIND.EFF - Cast Spell SRDBLIND.spl
COPY ~subrace/eff/effect.eff~ ~override/srdblind.eff~
  WRITE_LONG  0x10 146
  WRITE_LONG  0x14 2
  WRITE_LONG  0x20 1
  WRITE_LONG  0x24 1
  WRITE_SHORT 0x2c 100
  WRITE_ASCII 0x30 ~srdblind~ (8)

COPY ~subrace/spl/spell.spl~ ~override/srdblind.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode=321 target=2 timing=1 STR_VAR resource="srdblind" END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=318 target=2 parameter2=%notoutdoor% duration=1 STR_VAR resource="srdblind" END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=318 target=2 parameter2=90 duration=1 STR_VAR resource="srdblind" END
  //-1 THAC0
  LPF ADD_SPELL_EFFECT INT_VAR opcode=278 target=2 parameter1="-1" duration=60 END
  //-1 Saves
  LPF ADD_SPELL_EFFECT INT_VAR opcode=325 target=2 parameter1="-1" duration=60 END
  //Hide in shadows
  LPF ADD_SPELL_EFFECT INT_VAR opcode=275 target=2 parameter1="-5" duration=60 END
  //Open locks
  LPF ADD_SPELL_EFFECT INT_VAR opcode=90 target=2 parameter1="-5" duration=60 END
  //Find traps
  LPF ADD_SPELL_EFFECT INT_VAR opcode=91 target=2 parameter1="-5" duration=60 END
  //Pick pockets
  LPF ADD_SPELL_EFFECT INT_VAR opcode=92 target=2 parameter1="-5" duration=60 END
  //Move silently
  LPF ADD_SPELL_EFFECT INT_VAR opcode=59 target=2 parameter1="-5" duration=60 END
  //Set trap
  LPF ADD_SPELL_EFFECT INT_VAR opcode=277 target=2 parameter1="-5" duration=60 END
  //Visual range
  LPF ADD_SPELL_EFFECT INT_VAR opcode=262 target=2 parameter1="-4" duration=60 END
  //Portrait icon
  LPF ADD_SPELL_EFFECT INT_VAR opcode=142 target=2 parameter2=8  duration=60 END


//Hide in shadows no outdoors
//SRSVSHD.EFF - Apply effect list SRSVSHD.spl
COPY ~subrace/eff/effect.eff~ ~override/srsvshd.eff~
  WRITE_LONG  0x10 146
  WRITE_LONG  0x14 2
  WRITE_LONG  0x20 1
  WRITE_LONG  0x24 1
  WRITE_SHORT 0x2c 100
  WRITE_ASCII 0x30 ~srsvshd~ (8)

COPY ~subrace/spl/spell.spl~ ~override/srsvshd.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode=321 target=2 timing=1 STR_VAR resource="srsvshd" END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=318 target=2 parameter2=%outdoor% duration=1 STR_VAR resource="srsvshd" END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=275 target=2 duration=60 parameter1=10 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=91 target=2 duration=60 parameter1=10 END
//BLOCKEND

//BLOCK NPC
COPY ~subrace/spl/spell.spl~ ~override/sr_vcba.spl~
  //Portrait icon
  LPF ADD_SPELL_EFFECT INT_VAR opcode=142 target=2 timing=9 parameter2=text_drow END
  //Set spell state
  LPF ADD_SPELL_EFFECT INT_VAR opcode=328 target=2 timing=9  parameter2=%CRE_BLINDED_IWD% special=1  END
   //Find traps +10
  LPF ADD_SPELL_EFFECT INT_VAR opcode=91 target=2 timing=9 parameter1=10 END
   //Save vs. spells +1
  LPF ADD_SPELL_EFFECT INT_VAR opcode=37 target=2 timing=9 parameter1=1 END
   //Give innate ability
  LPF ADD_SPELL_EFFECT INT_VAR opcode=171 target=2 timing=9  STR_VAR resource="srffire" END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=171 target=2 timing=9  STR_VAR resource="srffire" END
  LPF ADD_SPELL_EFFECT INT_VAR opcode=171 target=2 timing=9  STR_VAR resource="srffire" END
   //Day blindness
  LPF ADD_SPELL_EFFECT INT_VAR opcode=272 target=2 timing=9 parameter1=6 parameter2=3  STR_VAR resource="srdblind" END
  //XP bonus - 90%
  LPF ADD_SPELL_EFFECT INT_VAR opcode=104 target=2 timing=9 parameter1=90 parameter2=2 END

ACTION_FOR_EACH scr IN VICONIA_ BDVICONI VICONIA VICO25 BAELOTH BDBAELOT BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%scr%.bcs~ THEN BEGIN
  	OUTER_SPRINT ~SUBRA~ ~VCBA~
  	OUTER_SET lc_subr = 3
    EXTEND_TOP ~%scr%.bcs~ ~subrace/baf/sr_subr.baf~ EVALUATE_BUFFER
  END
END

COPY ~subrace/spl/spell.spl~ ~override/sr_haer.spl~
  //Portrait icon
  LPF ADD_SPELL_EFFECT INT_VAR opcode=142 target=2 timing=9 parameter2=text_tiefling END
  //Give innate ability
  LPF ADD_SPELL_EFFECT INT_VAR opcode=171 target=2 timing=9  STR_VAR resource="srblind" END
  //XP bonus - 95%
  LPF ADD_SPELL_EFFECT INT_VAR opcode=104 target=2 timing=9 parameter1=95 parameter2=2 END

ACTION_FOR_EACH scr IN HAERDALI HAER25 BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%scr%.bcs~ THEN BEGIN
    OUTER_SPRINT ~SUBRA~ ~HAER~
    OUTER_SET lc_subr = 2
    EXTEND_TOP ~%scr%.bcs~ ~subrace/baf/sr_subr.baf~ EVALUATE_BUFFER
  END
END

COPY ~subrace/spl/spell.spl~ ~override/sr_cael.spl~
  //Portrait icon
  LPF ADD_SPELL_EFFECT INT_VAR opcode=142 target=2 timing=9 parameter2=text_aasimar END
   //Acid resistance +15
  LPF ADD_SPELL_EFFECT INT_VAR opcode=27 target=2 timing=9 parameter1=15 END
   //Electricity resistance +15
  LPF ADD_SPELL_EFFECT INT_VAR opcode=29 target=2 timing=9 parameter1=15 END
   //Infravision
  LPF ADD_SPELL_EFFECT INT_VAR opcode=63 target=2 timing=9 END
  //Give innate ability
  LPF ADD_SPELL_EFFECT INT_VAR opcode=171 target=2 timing=9  STR_VAR resource="srsnscoh" END
  //XP bonus - 95%
  LPF ADD_SPELL_EFFECT INT_VAR opcode=104 target=2 timing=9 parameter1=95 parameter2=2 END

ACTION_FOR_EACH scr IN BDCAELAR BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%scr%.bcs~ THEN BEGIN
	OUTER_SET lc_subr = 1
    OUTER_SPRINT ~SUBRA~ ~CAEL~
    EXTEND_TOP ~%scr%.bcs~ ~subrace/baf/sr_subr.baf~ EVALUATE_BUFFER
  END
END
//BLOCKEND

//BLOCK DROW_DUERGAR
ACTION_FOR_EACH cre IN bddrowf2 bddrowfm chevil06 cuguard drofod01 drofod03 drow01 drow03 drow06 loveone3 ohbdro01 sendro01 sendro03 sendro05 senfod01 sengua05 suraam uddrow27 uddrow28 udlesa udrunner udsola01 udsola02
                       bdkaelet bdshapur chevil07 cuardul cuphaer drofod02 drofod04 drow02 drow04 drow05 drow07 gortan3 gorwom04 ohbdro04 sendro02 senfod02 udardul uddrow29 uddrow31 udimrae udphae01 udphae02 vicpri01 bdumar
                       drowsor drowspe drowvan malavon malavons ginafae nym 
                       DIRTLLEW
                       l#nsnym BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%cre%.cre~ BEGIN
		COPY_EXISTING ~%cre%.cre~ ~override~
			//Set spell state
			LPF ADD_CRE_EFFECT INT_VAR opcode=328 target=1 timing=9  parameter2=%CRE_BLINDED_IWD% special=1  END
	END
END
////BLOCKEND

//BLOCK CHARACTER RECORD

COPY_EXISTING ~ui.menu~ ~override~
	LPM SHOW_IN_CHARACTER_RECORD
	BUT_ONLY_IF_IT_CHANGES
//BLOCKEND
